# 
FROM python:3.9

# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./  /code

COPY ./start.sh /start.sh
RUN chmod a+x /start.sh

# 
CMD ["bash","start.sh"]
